### ISSUE TITLE
define some analytical tasks for the dataset usage 

### ISSUE THREAD

**Issue by parasteh** [hky365/Global-Data-Sharing-Initiative-#1]
Hi there, I tried to understand what kind of ML task can be done on this dataset but had no success, for example, do you think there could be a prediction task to conduct an analysis toward a specific measure?

**Comment by hky365** [comment]
Dear Parasteh,

We have updated the description of the project with access to the dataset that has been used in this particular study.

There can be a range of classification and regression tasks that can be done with this dataset; however, these things are really researcher specific. The PhysioNet repository also contains a detailed description of the dataset which can help you formulate your research question.

Good luck with you research!

Best regards,
Hamza
